led:
  count: 240
  pin: 18
  freq: 800000 #800khz
  dma: 10
  brightness: 255
  invert: False
  channel: 0

log:
  path: "netled.log"
  levels:
    info: True
    warning: True
    error: True
    critical: True

net:
  packet_size: 1024
  default_port: 2425
