led:
  count: 240
  pin: 18
  freq: 800000 #800khz
  dma: 10
  brightness: 255
  invert: False
  channel: 0

log:
  path: "netled.log"
  levels:
    verbose: False
    info: True
    warning: True
    error: True
    critical: True

net:
  buffer_size: 4096
  default_port: 2425

audio:
  chunk: 1024
  channels: 2
  rate: 44100
